### ISSUE TITLE
Component Not Creating Sensor for Latest TV Shows

### ISSUE THREAD

**Issue by coopermf** [gcorgnet/sensor.emby_upcoming_media#1]
Hey, I tried out this custom component today with the newest version of the Upcoming Media Card and really appreciate all the work. However, the component seems to be working for fetching the latest Movies and displaying them properly in the card but fails to create a sensor for the latest TV shows added. I'm a noob to most of this stuff but let me know if there's anything I can do to help debug. I've attached my home assistant logs and this is what my config file looks like
 
sensor:
- platform: emby_upcoming_media
  api_key: *****************************************
  user_id: *****************************************
  host: 192.168.1.28
  port: 8096
  ssl: false
  max: 5
  include:
    - TV
    - Movies

[home-assistant.log](https://github.com/gcorgnet/sensor.emby_upcoming_media/files/3693844/home-assistant.log)

**Comment by gcorgnet** [comment]
Hey, what is the actual name of your library in Emby? Is it "TV" ?

**Comment by coopermf** [comment]
Yes, the library is just named "TV" but removing include from the config yields the same result. Only sensor.emby_latest_movies is created.

**Comment by coopermf** [comment]
Actually this is not quite true, it also generates sensor.emby_latest_playlists but fails to generate a sensor for my libraries "TV" and "Music"

**Comment by TheRealLouCipher** [comment]
I also get this. Sensor for tv shows fails to setup. Logs shows the following:

````2019-11-04 20:32:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 317, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 145, in device_state_attributes
    timeobject = timedelta(microseconds=show["RunTimeTicks"] / 10)
KeyError: 'RunTimeTicks'

**Comment by TheDave1022** [comment]
I have a similar issue. I get 3 categories created out of 6 when not including any includes. 
sensor.emby_latest_collections
sensor.emby_latest_live_tv
sensor.emby_latest_movies

I'm missing TV shows, Recordings, and Music from detecting. I'm able to view this data from the API 
http://{server}:8096/Users/{user_id}/Views

**Comment by TheDave1022** [comment]
Working now. Thanks!

**Comment by LEJOUI** [comment]
I'm having a similiar error for the movies. 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 145, in device_state_attributes
    timeobject = timedelta(microseconds=show["RunTimeTicks"] / 10)
KeyError: 'RunTimeTicks'`

**Comment by TheRealLouCipher** [comment]
@LEJOUI Have you updated the sensor.py? There's not no new release that contains the fix unfortunately.

**Comment by LEJOUI** [comment]
Thanks. I thought it only was a fix for the tv series. But it did also solve the problem for the movies.

**Comment by LEJOUI** [comment]
So it did work fine, but now I'm getting this error and now it doesn't generate the latest tv shows. 
Any ideas?

`traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 159, in device_state_attributes
    show["Id"], show["ImageTags"]["Primary"]
KeyError: 'Primary`

**Comment by gcorgnet** [comment]
I released that fix, sorry about the delay.
