### ISSUE TITLE
Sensors only updating when reboot Home Assistant

### ISSUE THREAD

**Issue by feinen** [gcorgnet/sensor.emby_upcoming_media#27]
Sensors only updates when i reboot Home Assistant.

Logger: homeassistant.components.sensor
Source: custom_components/emby_upcoming_media/sensor.py:152
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:43:32 AM (2 occurrences)
Last logged: 11:43:33 AM

Error adding entities for domain sensor with platform emby_upcoming_media
Error while setting up emby_upcoming_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 586, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 247, in extra_state_attributes
    return self.handle_tv_show()
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 152, in handle_tv_show
    card_item["title"] = show["SeriesName"]
KeyError: 'SeriesName'

**Comment by ZenyoMaarten** [comment]
Same over here 🙄

**Comment by feinen** [comment]
Found a workaround for this.

use a automation to call this service to refresh:

service: homeassistant.update_entity
data: {}
target:
  entity_id: sensor.emby_latest_tv

**Comment by xlyralycanx** [comment]
Hi,
If you encounter further errors try [this version](https://github.com/xlyralycanx/sensor.emby_upcoming_media) instead.
