### ISSUE TITLE
Error while setting up component

### ISSUE THREAD

**Issue by darkenbula** [gcorgnet/sensor.emby_upcoming_media#5]
## Configuration

  - platform: emby_upcoming_media
    api_key: 28ea2########f148209e4b3b575e87a
    user_id: d19b42083bf849########f43bd85bc5
    host: 192.168.1.100
    port: 8096
    ssl: false
    max: 5

Add your logs here.
2020-04-13 18:29:49 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up emby_upcoming_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/emby_upcoming_media/sensor.py", line 159, in device_state_attributes
    show["Id"], show["ImageTags"]["Primary"]
KeyError: 'Primary'

**Comment by LEJOUI** [comment]
I had the same error. Couple of HA restarts seems to solve it. But it does come back sometimes.

**Comment by darkenbula** [comment]
Spot on, not sure what happened, but it's working brilliantly

**Comment by gcorgnet** [comment]
Closing for now as this seems to be fixed.
